variables:
  GIT_CLEAN_FLAGS: -n

stages:
  - development

after_script:
  - docker image prune -f
  - echo "done"

development:
  stage: development
  script:
    - docker-compose -f docker-compose.yml up -d --force-recreate --build dev-adm-recruitment
    - development
  only:
    - development